import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

/* =========================
   GENERAL FAQs
========================= */
const faqs = [
  {
    question: "What services do you provide?",
    answer:
      "We offer comprehensive psychiatric and psychological care, including individual therapy, family therapy, crisis intervention, and evidence-based treatments such as CBT and EMDR."
  },
  {
    question: "Do you offer telehealth or online consultations?",
    answer:
      "Yes, we provide secure and confidential online therapy sessions to ensure accessibility and flexibility for our patients."
  },
  {
    question: "How do I book an appointment?",
    answer:
      "You can book an appointment directly through our website, call our helpline, or visit our clinic in person. Same-day appointments may also be available."
  },
  {
    question: "Are your treatments confidential?",
    answer:
      "Absolutely. All consultations and treatments are 100% confidential and conducted under DHA licensing and regulations."
  }
];

/* =========================
   NURSING FAQs
========================= */
const nursingFaqs = [
  {
    question: "What should I expect during my first visit?",
    answer:
      "Our nurses will welcome you in a safe, non-judgmental environment, discuss your concerns, and perform a comprehensive assessment to understand your physiological, emotional and psychological needs."
  },
  {
    question: "How will my vitals be checked?",
    answer:
      "During your visit, our nurses will check important vital signs, including blood pressure, pulse rate, respiratory rate, oxygen saturation, and body temperature. We will also measure your weight and height to calculate your Body Mass Index (BMI), which helps assess whether your BMI is within a healthy range. This comprehensive check helps us understand your overall physical health and provide the best care for your mental wellbeing."
  },
  {
    question: "How will the nurse support me during treatment?",
    answer:
      "Nurses provide compassionate care, active listening, and guidance. We work with you to develop a personalized plan and support your recovery every step of the way"
  },
  {
    question: "Will my privacy and confidentiality be respected?",
    answer:
      "Absolutely. All patient information is kept strictly confidential. Nurses ensure your privacy at every step of care, so you can feel safe sharing your concerns."
  },
  {
    question: "Can my family be involved in my care?",
    answer:
      "Yes. With your consent, nurses provide education and guidance to family members, helping them understand your condition and supporting your recovery journey together."
  },
  {
    question: "How can my medical information be released?",
    answer:
      "Patients (or guardians for children) can authorize the release of their medical information using our Release Of Information (ROI) form. You can specify what information to share, who will receive it, and for what period. Consent can be revoked in writing at any time, and our team ensures all requests are handled securely and in compliance with DHA regulations."
  },
  {
    question: "Can I ask questions about my treatment or medications?",
    answer:
      "Absolutely. Our nurses encourage you to ask questions and ensure you understand your treatment plan and medications fully."
  },
  {
    question: "How are my prescription medications managed?",
    answer:
      "Prescriptions are electronically generated by our doctors and sent directly to the pharmacy, linked to the patient’s Emirates ID. Patients can collect their medications from the pharmacy using their Emirates ID. The Professional pharmacists provide full guidance regarding your medications, including how and when to take them, correct dosages, possible interactions, and potential side effects. We are also available to answer any questions or provide clarifications to ensure safe and effective use"
  },
  {
    question: "How can I get a medication refill?",
    answer:
      "When your prescribed medication is finished and you need to continue treatment, you can confirm with your doctor. Once approved, you can request a new prescription. Our team is available to assist you with this process and answer any questions to ensure uninterrupted and safe medication use."
  },
  {
    question: "Is wheelchair assistance available at the clinic?",
    answer:
      "Yes. Wheelchair assistance is available for patients who are elderly, people of determination, or those with physical health conditions, such as post-surgery recovery or other medical limitations. Our trained nursing staff ensures safe and comfortable mobility throughout the clinic, facilitating access to all areas with care, respect, and dignity."
  },
  {
    question: "What emergency assistance is available at the clinic?",
    answer:
      "Our clinic is staffed by DHA-registered nurses who hold full certification in Basic Life Support (BLS), Advanced Cardiac Life Support (ACLS), and Pediatric Advanced Life Support (PALS) through the American Heart Association. The clinic is equipped with all necessary emergency treatment equipment, and our team is prepared to provide immediate care in the event of a medical emergency. We follow established emergency management protocols and ensure patient safety until transfer to a hospital setting, if required."
  },
  {
    question: " How can I request a medical report?",
    answer:
      "Patients can request their medical reports for personal use or official purposes. Before releasing any report, we ensure that patient confidentiality is maintained and obtain the patient’s consent. Our team assists in preparing the report accurately and securely in compliance with DHA regulations and UAE laws."
  },
  {
    question: "Can the clinic provide medical reports for school or educational purposes?",
    answer:
      "Yes. We provide reports for schools or educational institutions, such as attendance records, treatment summaries, or health updates. Prior to release, we confirm the patient’s preferences and obtain consent, ensuring confidentiality is fully maintained throughout the process."
  }
];

const NURSING_VISIBLE_COUNT = 6;

const FAQSection = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="py-20 bg-gradient-to-br from-background to-muted/20">
      <div className="container mx-auto px-4">

        {/* =========================
            SCOPED STYLES
        ========================= */}
        <style>{`
          .nursing-scroll {
            scrollbar-width: none;
            -ms-overflow-style: none;
          }

          .nursing-scroll::-webkit-scrollbar {
            width: 0px;
            height: 0px;
          }

          .nursing-scroll:hover {
            scrollbar-width: thin;
          }

          .nursing-scroll:hover::-webkit-scrollbar {
            width: 6px;
          }

          .nursing-scroll:hover::-webkit-scrollbar-thumb {
            background-color: rgba(120,120,120,0.4);
            border-radius: 999px;
          }
        `}</style>

        {/* HEADER */}
        <div className="text-center space-y-4 mb-12">
          <Badge variant="secondary">Frequently Asked Questions</Badge>
          <h2 className="text-3xl md:text-4xl font-bold">
            Your Questions,{" "}
            <span className="bg-gradient-primary bg-clip-text text-transparent">
              Answered
            </span>
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Find quick answers to common questions about our services,
            appointments, and care process.
          </p>
        </div>

        {/* GENERAL FAQs */}
        <div className="max-w-3xl mx-auto space-y-4 mb-16">
          {faqs.map((faq, index) => (
            <Card key={faq.question}>
              <button
                className="w-full flex items-center justify-between px-6 py-4 text-left"
                onClick={() =>
                  setOpenIndex(openIndex === index ? null : index)
                }
              >
                <CardHeader className="p-0">
                  <CardTitle className="text-lg">
                    {faq.question}
                  </CardTitle>
                </CardHeader>

                <ChevronDown
                  className={`h-5 w-5 transition-transform ${
                    openIndex === index ? "rotate-180" : ""
                  }`}
                />
              </button>

              {openIndex === index && (
                <CardContent className="px-6 pb-6 text-muted-foreground">
                  {faq.answer}
                </CardContent>
              )}
            </Card>
          ))}
        </div>

        {/* NURSING HEADER */}
        <div className="text-center space-y-3 mb-6">
          <Badge variant="outline">Nursing Services FAQs</Badge>
          <h3 className="text-2xl font-semibold">
            Nursing Care Questions
          </h3>
        </div>

        {/* SCROLLABLE NURSING FAQs */}
        <div className="relative max-w-3xl mx-auto">

          {/* Fade Top */}
          <div className="pointer-events-none absolute top-0 left-0 right-0 h-6 bg-gradient-to-b from-background to-transparent z-10" />

          <div className="max-h-[420px] overflow-y-auto space-y-4 pr-2 nursing-scroll">

            {nursingFaqs.map((faq, index) => {
              const nursingIndex = index + faqs.length;

              return (
                <Card key={faq.question}>
                  <button
                    className="w-full flex items-center justify-between px-6 py-4 text-left"
                    onClick={() =>
                      setOpenIndex(
                        openIndex === nursingIndex ? null : nursingIndex
                      )
                    }
                  >
                    <CardHeader className="p-0">
                      <CardTitle className="text-lg">
                        {faq.question}
                      </CardTitle>
                    </CardHeader>

                    <ChevronDown
                      className={`h-5 w-5 transition-transform ${
                        openIndex === nursingIndex ? "rotate-180" : ""
                      }`}
                    />
                  </button>

                  {openIndex === nursingIndex && (
                    <CardContent className="px-6 pb-6 text-muted-foreground">
                      {faq.answer}
                    </CardContent>
                  )}
                </Card>
              );
            })}

          </div>

          {/* Fade Bottom */}
          <div className="pointer-events-none absolute bottom-0 left-0 right-0 h-6 bg-gradient-to-t from-background to-transparent" />

        </div>

      </div>
    </section>
  );
};

export default FAQSection;
